resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- task: Bash@3
  displayName: 'Install dependencies'
  inputs:
    targetType: 'filePath'
    filePath: setup/setup.sh

- task: AzureCLI@1
  displayName: 'Prep Environment for model creation'
  inputs:
    azureSubscription: devopsaisec_service_connection
    scriptLocation: inlineScript
    inlineScript: 'python services/10_prepEnvModelCreation_sec.py $(amls-name) $(subscription-id) $(rg-name) $(dbr-url) $(dbr-key)'
    workingDirectory: project

- task: AzureCLI@1
  displayName: 'Build model using Databricks'
  inputs:
    azureSubscription: devopsaisec_service_connection
    scriptLocation: inlineScript
    inlineScript: 'python services/20_buildModelDatabricks_sec.py $(amls-name) $(subscription-id) $(rg-name) $(dbr-url) $(dbr-key) $(stor-name) $(stor-container) $(dbr-secretscope)'
    workingDirectory: project

- task: AzureCLI@1
  displayName: 'Create image from model'
  inputs:
    azureSubscription: devopsaisec_service_connection
    scriptLocation: inlineScript
    inlineScript: 'python services/30_createImageFromModel_sec.py $(amls-name) $(subscription-id) $(rg-name)'
    workingDirectory: project

- task: AzureCLI@1
  displayName: 'Key rollover Databricks token'
  inputs:
    azureSubscription: 'devopsaisec_service_connection'
    scriptPath: 'project/services/60_keyrollover_sec.sh'
    arguments: '$(dbr-key) $(dbr-token) $(dbr-url) $(keyvault-name) 10'
    workingDirectory: project

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'